version: "3.8"

services:
  blog-redis:
    image: redis:7
    platform: linux/amd64
    networks:
      - blog
    container_name: blog-redis
    hostname: blog-redis
    ports:
      - "56379:6379"
    volumes:
      - /Users/nogyeongtae/data/redis:/var/lib/redis

  blog-mysql:
    image: mysql:8.0.22
    platform: linux/amd64
    networks:
      - blog
    ports:
      - "43306:3306"
    container_name: blog-mysql
    hostname: blog-mysql
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: nokt
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - /Users/nogyeongtae/data/mysql:/var/run/mysql

  blog-neo4j:
    image: neo4j:5.12
    platform: linux/amd64
    networks:
      - blog
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /Users/nogyeongtae/data/neo4j:/var/run/neo4j
    environment:
      NEO4J_AUTH: neo4j/nokt12345678

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - blog
    container_name: blog-app
    depends_on:
      - blog-mysql
      - blog-neo4j
    ports:
      - "8099:8099"

networks:
  blog:
    external: true